const productData = {
    users: [],
    products: [
        {
            name: "Product 1",
            slug: "product-1",
            description: "Description for Product 1",
            price: 19.99,
            quantity: 50,
            sold: 10,
            shipping: 5.99,
            image: "default.jpg",
            category: "65968a3fdf6c4897301a204e",
        },
        {
            name: "Product 2",
            slug: "product-2",
            description: "Description for Product 2",
            price: 29.99,
            quantity: 30,
            sold: 5,
            shipping: 7.99,
            image: "default.jpg",
            category: "65968a3fdf6c4897301a204e",
        },
        {
            name: "Product 3",
            slug: "product-3",
            description: "Description for Product 3",
            price: 39.99,
            quantity: 20,
            sold: 15,
            shipping: 9.99,
            image: "default.jpg",
            category: "65968a3fdf6c4897301a204e",
        },
        {
            name: "Product 4",
            slug: "product-4",
            description: "Description for Product 4",
            price: 49.99,
            quantity: 40,
            sold: 8,
            shipping: 12.99,
            image: "default.jpg",
            category: "65968c6f0a1dbff16a4c3dd3",
        },
        {
            name: "Product 5",
            slug: "product-5",
            description: "Description for Product 5",
            price: 59.99,
            quantity: 25,
            sold: 12,
            shipping: 14.99,
            image: "default.jpg",
            category: "65968c6f0a1dbff16a4c3dd3",
        },
    ],
};
module.exports = productData;
